// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// PLACEHOLDER FILE — this project has not been connected to a real Firebase
/// project yet. Run `firebase login` then `flutterfire configure` from the
/// project root to overwrite this file with your real project's config.
/// See README.md for the full setup steps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run `flutterfire configure` to generate real options.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcEIvhuGq6CimFLR018wwO23Wljlgojt4',
    appId: '1:794788631267:web:68b97d143e1e3779136bd6',
    messagingSenderId: '794788631267',
    projectId: 'careconnect-d1e99',
    authDomain: 'careconnect-d1e99.firebaseapp.com',
    storageBucket: 'careconnect-d1e99.firebasestorage.app',
    measurementId: 'G-W0SYLR0HV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4V7BP0bZqqE2ZIaVM8hdmf-hFWhDd9FM',
    appId: '1:794788631267:android:3a4d3adf8dc1ff5d136bd6',
    messagingSenderId: '794788631267',
    projectId: 'careconnect-d1e99',
    storageBucket: 'careconnect-d1e99.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ax8HCsyUXVEiABDLpFStB-A9Ogrg31I',
    appId: '1:794788631267:ios:6c8d5038fb06f842136bd6',
    messagingSenderId: '794788631267',
    projectId: 'careconnect-d1e99',
    storageBucket: 'careconnect-d1e99.firebasestorage.app',
    iosBundleId: 'com.careconnect.careconnect',
  );
}
